### ISSUE TITLE
GoogleTakeout Directory ID

### ISSUE THREAD

**Issue by ucb** [Fallenstedt/google-takeout-sucks#7]
Hi,

Where do you find `GoogleTakeout Directory ID`? When I am in "Manage your exports", I see `rapt=...`, but the string there obviously defines all takeouts. I have tried it just in case, but that throws an error.

I do not see that takeout folder is visible, when i My Drive, `https://drive.google.com/drive/u/0/my-drive`

I have also tried using ids from `rapt=...` of individual file lines in the download, but they give me an error too.

Help is greatly appreciated :)

**Comment by Fallenstedt** [comment]
Hey @ucb , I just saw this, I'm sorry I am very bad at paying attention to notifications because I get so many. 
The directory id is in the URL when you view your takeout directory in Google Drive web. It's a very, very long string. 
![drive-id](https://github.com/user-attachments/assets/9902925c-40b0-465a-8779-6cd82eae01df)
